# This is a config for E2B sandbox template.
# You can use template ID (kvi2idsv62233gkzkfsd) or template name (asuna-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("asuna-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("asuna-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('asuna-test2')

team_id = "2d232f9a-8390-497a-87ba-9f49321f1b82"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "asuna-test2"
template_id = "kvi2idsv62233gkzkfsd"
